package br.com.marlan.dao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class Basi030Dao extends Dao {
	
//	ABERTO_TUBULAR
//	AGULHAS_FALHADAS
//	APROVEIT_MEDIO
//	ARTIGO
//	ARTIGO_APROVEIT
//	ARTIGO_COTAS
//	CAIXAS
//	CEST
//	CGC_CLIENTE_2
//	CGC_CLIENTE_4
//	CGC_CLIENTE_9
//	CLASSIFIC_FISCAL
//	COD_ATRIBUTO_01
//	COD_ATRIBUTO_02
//	COD_ATRIBUTO_03
//	COD_ATRIBUTO_04
//	COD_ATRIBUTO_05
//	COD_ATRIBUTO_06
//	COD_ATRIBUTO_07
//	COD_ATRIBUTO_08
//	COD_ATRIBUTO_09
//	COD_ATRIBUTO_10
//	COD_BAR_POR_CLI
//	COD_EMBALAGEM
//	CODIGO_CONTABIL
//	COD_TIPO_AVIAMENTO
//	COLECAO_CLIENTE
//	COMPOSICAO_01
//	COMPOSICAO_01_INGLES
//	COMPOSICAO_02
//	COMPOSICAO_02_INGLES
//	COMPOSICAO_03
//	COMPOSICAO_03_INGLES
//	COMPOSICAO_04
//	COMPOSICAO_04_INGLES
//	COMPOSICAO_05
//	COMPOSICAO_05_INGLES
//	COMPOSICAO_06
//	COMPOSICAO_07
//	COMPOSICAO_08
//	COMPOSICAO_09
//	COMPOSICAO_10
//	COMPRADO_FABRIC
//	COMP_SERRA_FITA
//	CONF_ALTERA_PROG
//	CONTA_ESTOQUE
//	COR_DE_ESTOQUE
//	COR_DE_PRODUCAO
//	COR_DE_SORTIDO
//	COSTURA_ABA
//	DATA_MOV_CILINDRO
//	DEMANDA
//	DESCR_COMPLEMENTAR
//	DESCR_ESPANHOL
//	DESCRICAO_TAG1
//	DESCRICAO_TAG2
//	DESCR_INGLES
//	DIAS_MATURACAO
//	DIV_PROD
//	DOC_REFERENCIAL
//	ENGOMACAO
//	ESTAGIO_ALTERA_PROGRAMADO
//	ESTAMPA_IMPRESSA
//	FACCAO_PILOTO
//	FAMILIA_ATRIBUTO
//	FINURA_PILOTO
//	FORMACAO_AGULHAS
//	FORMA_MOLDE
//	GRADUACAO_PILOTO
//	GRUPO_AGRUPADOR
//	GRUPO_TECIDO_CORTE
//	IMP_INF_EMPRESA_TAG
//	IND_ENVIA_INFOTINT
//	INDICE_REAJUSTE
//	ITEM_BAIXA_ESTQ
//	LARGURA_CILINDRO
//	LARGURA_ESTAMPA
//	LIGAMENTO
//	LINHA_PRODUTO
//	LOTE_ESTOQUE
//	MAQUINA_PILOTO
//	METROS_LINEARES
//	MODULAR
//	MULTIPLICADOR
//	NUMERO_MOLDE
//	NUMERO_PONTOS_LASER
//	NUMERO_ROTEIRO
//	NUM_PROGRAMA
//	NUM_SOL_DESENV
//	NVLPRECOMONTAGEM
//	OBSERVACAO
//	OBSERVACAO2
//	OBSERVACAO3
//	OPCAO_VENDA_COR
//	ORIGEM_MERCADORIA
//	ORIGEM_PRECO_CUSTO
//	PARTE_COMPOSICAO_01
//	PARTE_COMPOSICAO_02
//	PARTE_COMPOSICAO_03
//	PARTE_COMPOSICAO_04
//	PARTE_COMPOSICAO_05
//	PARTE_COMPOSICAO_06
//	PARTE_COMPOSICAO_07
//	PARTE_COMPOSICAO_08
//	PARTE_COMPOSICAO_09
//	PARTE_COMPOSICAO_10
//	PARTE_CONJUNTO_01
//	PARTE_CONJUNTO_02
//	PARTE_CONJUNTO_03
//	PARTE_CONJUNTO_04
//	PARTE_CONJUNTO_05
//	PARTE_CONJUNTO_06
//	PARTE_CONJUNTO_07
//	PARTE_CONJUNTO_08
//	PARTE_CONJUNTO_09
//	PARTE_CONJUNTO_10
//	PASTA_BANHO
//	PERC_COMPOSICAO1
//	PERC_COMPOSICAO10
//	PERC_COMPOSICAO2
//	PERC_COMPOSICAO3
//	PERC_COMPOSICAO4
//	PERC_COMPOSICAO5
//	PERC_COMPOSICAO6
//	PERC_COMPOSICAO7
//	PERC_COMPOSICAO8
//	PERC_COMPOSICAO9
//	PERCENT_DESCONTO
//	PERCENT_PERDA_1
//	PERCENT_PERDA_2
//	PERCENT_PERDA_3
//	PERCENTUAL_AMACIANTE
//	PERC_2_QUALIDADE
//	PERIMETRO_CORTE
//	PERS_BORDADO_PILOTO
//	PERS_LAVACAO_PILOTO
//	PERSONALIZACAO_PILOTO
//	PERS_SERIGRAFIA_PILOTO
//	PESO_ACABAMENTO_PILOTO
//	PESO_AMOSTRA
//	PESO_BRUTO_PILOTO
//	PONTOS_POR_CM
//	PRODUTO_PROTOTIPO
//	PRODUTO_VENDA
//	PROGRAMADOR_PILOTO
//	PROGRAMA_PILOTO
//	PUBLICO_ALVO
//	RAPORTAGEM
//	REFERENCIA_AGRUPADOR
//	REFERENCIA_DESENV
//	REF_ORIGINAL
//	RESPONSAVEL
//	RISCO_PADRAO
//	SERIE_TAMANHO
//	SIMBOLO_1
//	SIMBOLO_10
//	SIMBOLO_2
//	SIMBOLO_3
//	SIMBOLO_4
//	SIMBOLO_5
//	SIMBOLO_6
//	SIMBOLO_7
//	SIMBOLO_8
//	SIMBOLO_9
//	SORTIMENTO_DIVERSOS
//	SUB_AGRUPADOR
//	TAB_RENDIMENTO
//	TAMANHO_ABA
//	TAMANHO_AMOSTRA
//	TAMANHO_FILME
//	TECELAGEM_PILOTO
//	TEMPO_LASER
//	TIPO_CODIGO_EAN
//	TIPO_ESTAMPA
//	TIPO_PRODUTO
//	TIPO_TAG_EAN
//	TOMBAMENTO_ABA
//	ULTIMA_COR_SORTIDA
//	UNIDADE_MEDIDA
//	VARIACAO_CORES
//	DESCR_REFERENCIA
	private String descricao;
//	NIVEL_ESTRUTURA
	private Integer nivel;
//	REFERENCIA
	private String referencia;
//	COLECAO
	private Integer codColecao;
	
	public Basi030Dao(Integer nivel, String referencia) {
		super();
		try {
			String query = "SELECT * FROM BASI_030 PROD WHERE PROD.NIVEL_ESTRUTURA = ? AND PROD.REFERENCIA = ?";
			PreparedStatement stmt = this.getConn().prepareStatement(query);
			stmt.setInt(1, nivel);
			stmt.setString(2, referencia);
			ResultSet res = stmt.executeQuery();
			while (res.next()) {
				this.setNivel(res.getInt("NIVEL_ESTRUTURA"));
				this.setReferencia(res.getString("REFERENCIA"));
				this.setCodColecao(res.getInt("COLECAO"));
				this.setDescricao(res.getString("DESCR_REFERENCIA"));
			}
			res.close();
			stmt.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public String getReferencia() {
		return referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Integer getCodColecao() {
		return codColecao;
	}

	public void setCodColecao(Integer codColecao) {
		this.codColecao = codColecao;
	}

}
